<?php

/**
 * @file
 * Sample assets module.
 */

/**
 * Implements hook_page_attachments().
 */
function sample_assets_page_attachments(array &$attachments) {
  // Add our custom CSS.
  $attachments['#attached']['library'][] = 'sample_assets/sample_assets.custom_css';
  // Add our custom JS.
  $attachments['#attached']['library'][] = 'sample_assets/sample_assets.custom_js';
  // Now add our asset bundle. This will automatically include a JS and CSS
  // file.
  $attachments['#attached']['library'][] = 'sample_assets/sample_assets.bundle';
}
